routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FormFieldController;
use App\Http\Controllers\FormTemplateController;
use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Example route in routes/web.php

Route::get('/admin/dashboard', function () {
    return view('dashboard');
})->middleware(['auth','role:Administrator', 'verified'])->name('admin.dashboard');
Route::get('/user/dashboard', function () {
    return view('dashboard');
})->middleware(['auth','role:User', 'verified'])->name('user.dashboard');

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

require __DIR__.'/auth.php';

Route::resource('categories', CategoryController::class);
Route::resource('form-templates', FormTemplateController::class);
Route::resource('form-templates', FormFieldController::class);

app/Models/FormTemplate.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FormTemplate extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function formFields()
    {
        return $this->hasMany(FormField::class);
    }

    public function formSubmissions()
    {
        return $this->hasMany(FormSubmission::class);
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }
}

app/Http/Controllers/FormTemplateController.php
<?php
namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\FormTemplate;
use Illuminate\Http\Request;

class FormTemplateController extends Controller
{
    public function index()
    {
        $formTemplates = FormTemplate::all();
        return view('form_templates.index', compact('formTemplates'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('form_templates.create', compact('categories'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
        ]);

        FormTemplate::create([
            'category_id' => $request->input('category_id'),
            'title' => $request->input('title'),
            'description' => $request->input('description'),
            'created_by' => auth()->user()->id,
        ]);

        return redirect()->route('form-templates.index')->with('success', 'Form template created successfully.');
    }

    public function edit(FormTemplate $formTemplate)
    {
        $categories = Category::all();
        return view('form_templates.edit', compact('formTemplate', 'categories'));
    }

    public function update(Request $request, FormTemplate $formTemplate)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id',
            'title' => 'required|string|max:255',
            'description' => 'nullable|string',
        ]);

        $formTemplate->update([
            'category_id' => $request->input('category_id'),
            'title' => $request->input('title'),
            'description' => $request->input('description'),
        ]);

        return redirect()->route('form-templates.index')->with('success', 'Form template updated successfully.');
    }

    public function destroy(FormTemplate $formTemplate)
    {
        $formTemplate->delete();
        return redirect()->route('form-templates.index')->with('success', 'Form template deleted successfully.');
    }
}

resources/views/form-templates/create.blade.php
@extends('layouts.app_one')

@section('content')
<div class="container">
    <h1>Create Form Template</h1>

    <form method="POST" action="{{ route('form-templates.store') }}">
        @csrf
        <div class="form-group">
            <label for="category_id">Category</label>
            <select class="form-control" id="category_id" name="category_id">
                @foreach($categories as $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Create</button>
    </form>
</div>
@endsection

resources/views/form-templates/edit.blade.php
@extends('layouts.app_one')

@section('content')
<div class="container">
    <h1>Edit Form Template</h1>

    <form method="POST" action="{{ route('form-templates.update', $formTemplate) }}">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="category_id">Category</label>
            <select class="form-control" id="category_id" name="category_id">
                @foreach($categories as $category)
                    <option value="{{ $category->id }}" @if($category->id == $formTemplate->category_id) selected @endif>{{ $category->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" class="form-control" id="title" name="title" value="{{ $formTemplate->title }}" required>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control" id="description" name="description">{{ $formTemplate->description }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
</div>
@endsection

resources/views/form-templates/index.blade.php
@extends('layouts.app_one')

@section('content')
<div class="container">
    <h1>Form Templates</h1>

    @if(session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <a href="{{ route('form-templates.create') }}" class="btn btn-primary">Create Form Template</a>

    <table class="table mt-3">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Category</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($formTemplates as $formTemplate)
                <tr>
                    <td>{{ $formTemplate->title }}</td>
                    <td>{{ $formTemplate->description }}</td>
                    <td>{{ $formTemplate->category->name }}</td>
                    <td>
                        <a href="{{ route('form-templates.edit', $formTemplate) }}" class="btn btn-primary btn-sm">Edit</a>
                        <form method="POST" action="{{ route('form-templates.destroy', $formTemplate) }}" class="d-inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure you want to delete this form template?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No form templates found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</div>
@endsection